# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - gulpfile.js
  - tailwind.js
  - src
  # We additionally exclude the heavy static folders for speedier builds.
  - 5.x
  - designer
  - javadocs
  - userguide
